### ISSUE TITLE
Broken for schedule?

### ISSUE THREAD

**Issue by danwos** [namitkewat/serverless-plugin-tag-events#1]
I tried to use this nice plugin for creating tgs for  events in EventBridge, but I get the error
``functions.import.events[0].schedule': unrecognized property 'tags'``

The error is the same, as if the plugin would not be loaded (but it is).

Details of my config (extremely shorten):
```
service: example
plugins:
  - serverless-python-requirements
  - serverless-plugin-tag-events

functions:
  import:
    name: MyName
    handler: importer.lambda_handler
    events:
      - schedule:
          name: xyz
          rate: ...
          tags:
            test: foo
```
You see the config itself is not very special.

Version: serverless-plugin-tag-events@1.1.0

Installed via ``npm install serverless-plugin-tag-events@1.1.0``

Not sure how to debug any further...
